### ISSUE TITLE
About the generalization of the hybrid matching query setting

### ISSUE THREAD

**Issue by Zhangjiacheng144** [HDETR/H-Deformable-DETR#16]
Hi, thanks for such great work! I wonder if you test the generalization of the hybrid matching proposed in your paper. I tried to implement the hybrid matching queries on DINO-Deformable-DETR, and the performance degraded from 48.7 mAP to 46.5 under the standard 1x schedule, which seems the hybrid matching strategy in your paper cannot easily transform to other DETR-based object detectors. Hope to get your reply.

**Comment by PkuRainBow** [comment]
@Zhangjiacheng144 Thanks for your interest in our work and for sharing your interesting results. 

Indeed, we have not spent efforts on combining our approach to the complicated DINO-DETR due to two reasons: 

1. The one-to-many matching scheme might conflict with the denoising query scheme to some degree as both approaches highly depend on the extra introduced positive queries.
2. The gains of CDN/DN (DINO-DETR) highly depend on two key factors including (i) the explicit bounding box query formulation and (ii) label denoising. We believe the community needs to get rid of both factors if we want to generalize to broader vision tasks such as pose estimation.

Besides, **the recent Group-DETR already shows that a one-to-many matching scheme can also boost the performance of DINO-DETR, which is encouraging and non-trivial indeed.**

Last, we have got some stronger OD results than DINO-DETR, aka., AP=59+%, on COCO.

One contribution of our work is to deepen the community's understanding of "why and how DN-DETR/DINO-DETR works?".

**Comment by Zhangjiacheng144** [comment]
Ok, Thanks for your reply. BTW, are the results of AP=59+% on COCO still under the Deformable DETR-based detector taking the Swin-L(IN-22K) as the backbone? It's very appreciated to hear your sharing!

**Comment by PkuRainBow** [comment]
@Zhangjiacheng144 Please stay tuned for the status of this work.

**Comment by Zhangjiacheng144** [comment]
Ok, thanks a lot.
